title: Gaomin Wu # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/gaomin-wu-9a202512a/">LinkedIn</a> |
  <a href="https://github.com/gaominwu">GitHub</a>
  </p>

  <p align="justify">
  I am pursuing MS degree in Data Science at Center for Data Science, New York University.
  <br><br>
  My interests include Machine Learning, Nature Language Processing, Reinforcement Learning; 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
